spring:
  cloud:
    gateway:
      routes:
        - id: OrderService
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                  name: order-service
                  fallbackUri: forword:/orderFallback
        - id: PaymentService
          uri: lb://payment-service
          predicates:
              - Path=/payment/**
          filters:
          - name: CircuitBreaker
            args:
              name: payment-service
              fallbackUri: forward:/paymentFallback
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000



